const product = [
  {
    id: 1,
    title: "Blue Hat",
    CATEGORY: "GARDEN, GIFTS",
    price: "$159.00",
    discount: "$50.00",
    Offer: "35% OFF",
    new: "",
    Image: `https://www.portotheme.com/wordpress/porto/shop32/wp-content/uploads/sites/103/2019/10/shop32_product_1.jpg`,
  },
  {
    id: 2,
    title: "5G Phone",
    CATEGORY: "FURNITURE, GARDEN, MOTORS",
    price: "$299.00",
    discount: "$20.00",
    Offer: "",
    new: "New",
    Image: `https://www.portotheme.com/wordpress/porto/shop32/wp-content/uploads/sites/103/2019/10/shop32_product_7.jpg`,
  },
  {
    id: 3,
    title: "Brend Watch",
    CATEGORY: "Brend, GIFTS",
    price: "$359.00",
    discount: "$20.00",
    Offer: "",
    new: "",
    Image: `https://www.portotheme.com/wordpress/porto/classic-original/wp-content/uploads/sites/2/2016/06/project-1-2-400x400.jpg`,
  },
  {
    id: 4,
    title: "Men Black Sports Shoes",
    CATEGORY: " HOODIES, SHOES,",
    price: "$1,699.00",
    discount: "$1,999.00",
    Offer: "HOT",
    new: "",
    Image: `https://www.portotheme.com/wordpress/porto/gutenberg-shop4/wp-content/uploads/sites/116/2018/04/product-22.jpg`,
  },
  {
    id: 5,
    title: "Brown-Black Men Casual Glasses",
    CATEGORY: "CLOTHING, T-SHIRTS, WATCHES",
    price: "$101.00 – $111.00",
    discount: "",
    Offer: "",
    new: "",
    Image: `https://www.portotheme.com/wordpress/porto/gutenberg-shop4/wp-content/uploads/sites/116/2018/04/product-106-grey.jpg`,
  },
  {
    id: 6,
    title: "Ultimate 3D Bluetooth Speaker",
    CATEGORY: " CLOTHING, SHOES, T-SHIRTS",
    price: "$105.00 – $108.00",
    discount: "",
    Offer: "",
    new: "New",
    Image: `https://www.portotheme.com/wordpress/porto/gutenberg-shop4/wp-content/uploads/sites/116/2018/04/product-60.jpg`,
  },
  {
    id: 7,
    title: "Drone Pro",
    CATEGORY: "GARDEN, GIFTS",
    price: "$499.0",
    discount: "$550.00",
    Offer: "35% OFF",
    new: "",
    Image: `https://www.portotheme.com/wordpress/porto/shop36/wp-content/uploads/sites/179/2020/07/shop36_product1.jpg`,
  },
  {
    id: 8,
    title: "Palm Print Jacket",
    CATEGORY: " ACCESSORIES, FASHION, SPRING & AUTUMN, ",
    price: "$289.0",
    discount: "$20.00",
    Offer: "",
    new: "New",
    Image: `https://www.portotheme.com/wordpress/porto/shop36/wp-content/uploads/sites/179/2020/07/shop36_cat1.jpg`,
  },
  {
    id: 9,
    title: "Camera",
    CATEGORY: "CAMERAS, HOME ELECTRONIC, PHOTO SUPPLIES,",
    price: "$199.0",
    discount: "",
    Offer: "HOT",
    new: "",
    Image: `https://www.portotheme.com/wordpress/porto/shop36/wp-content/uploads/sites/179/2020/07/shop36_product6.jpg`,
  },
];
